INSERT ALL
    INTO PCG_COLOR (color_name) VALUES ('Red')
    INTO PCG_COLOR (color_name) VALUES ('Green')
    INTO PCG_COLOR (color_name) VALUES ('Blue')
    INTO PCG_COLOR (color_name) VALUES ('Yellow')
    INTO PCG_COLOR (color_name) VALUES ('Purple')
    INTO PCG_COLOR (color_name) VALUES ('Orange')
    INTO PCG_COLOR (color_name) VALUES ('Pink')
    INTO PCG_COLOR (color_name) VALUES ('Brown')
    INTO PCG_COLOR (color_name) VALUES ('Black')
    INTO PCG_COLOR (color_name) VALUES ('White')
SELECT * FROM dual;
SELECT * FROM PCG_COLOR;

CALL PCG_NEW_GAMEBOARD(123456, 3, 4, 5, 3);
SELECT count(*) FROM PCG_GAMEBOARD;
SELECT * FROM PCG_GAMEBOARD;
SELECT * FROM PCG_GAMEBOARD_PLAYER WHERE GAMEBOARD_ID = '123456';
SELECT * FROM PCG_GAMEBOARD_COLOR WHERE GAMEBOARD_ID = '123456';
SELECT * FROM PCG_GAMEBOARD_TILE WHERE GAMEBOARD_ID = '123456';
ROLLBACK;

SELECT USER, 'PCG_COLOR', count(*) FROM PCG_COLOR 
UNION ALL
SELECT USER, 'PCG_GAMEBOARD', count(*) FROM PCG_GAMEBOARD 
UNION ALL
SELECT USER, 'PCG_GAMEBOARD_COLOR', count(*) FROM PCG_GAMEBOARD_COLOR 
UNION ALL
SELECT USER, 'PCG_GAMEBOARD_PLAYER', count(*) FROM PCG_GAMEBOARD_PLAYER 
UNION ALL
SELECT USER, 'PCG_GAMEBOARD_TILE', count(*) FROM PCG_GAMEBOARD_TILE 
UNION ALL
SELECT USER, 'PCG_PLAYER', count(*) FROM PCG_PLAYER;

SELECT USER, t.* FROM PCG_GAMEBOARD t;

SELECT USER, t.* FROM PCG_GAMEBOARD_PLAYER t;

SELECT USER, t.* FROM PCG_GAMEBOARD_COLOR t;

SELECT USER
     , t.Gameboard_ID 
     , t.Tile_Row
     , count(*)
     , min(t.Tile_Col)
     , max(t.Tile_Col)
     , max(t.Player_ID)
     , max(t.Color_Name)
  FROM PCG_GAMEBOARD_TILE t
 GROUP BY t.Gameboard_ID, t.Tile_Row
 ORDER BY t.Gameboard_ID, t.Tile_Row;

 
GRANT EXECUTE on PCG_JOIN TO hc848;
GRANT EXECUTE on PCG_JOIN TO Ab4678;
GRANT EXECUTE on PCG_JOIN TO tjc375;
GRANT EXECUTE on PCG_JOIN TO je578;
GRANT EXECUTE on PCG_JOIN TO sy587;

CALL PCG_NEW_GAMEBOARD(987654,5,4,5,3);

CALL PCG_JOIN_GAMEBOARD(987654, 'ab4678');
CALL PCG_JOIN_GAMEBOARD(987654, 'tjc375');
CALL PCG_JOIN_GAMEBOARD(987654, 'JE578');
CALL PCG_JOIN_GAMEBOARD(987654, 'sys87');
INSERT INTO PCG_PLAYER (PLAYER_ID) VALUES('JE578');

SELECT * FROM PCG_PLAYER;

SELECT USER, 'PCG_COLOR', count(*) FROM PCG_COLOR
UNION ALL
SELECT USER, 'PCG_GAMEBOARD', count(*) FROM PCG_GAMEBOARD WHERE GAMEBOARD_ID = '987654'
UNION ALL
SELECT USER, 'PCG_GAMEBOARD_COLOR', count(*) FROM PCG_GAMEBOARD_COLOR WHERE GAMEBOARD_ID = '987654'
UNION ALL
SELECT USER, 'PCG_GAMEBOARD_PLAYER', count(*) FROM PCG_GAMEBOARD_PLAYER WHERE GAMEBOARD_ID = '987654'
UNION ALL
SELECT USER, 'PCG_GAMEBOARD_TILE', count(*) FROM PCG_GAMEBOARD_TILE WHERE GAMEBOARD_ID = '987654'
UNION ALL

SELECT USER, t.* FROM PCG_GAMEBOARD t
WHERE GAMEBOARD_ID = 987654;

SELECT USER, t.* FROM PCG_GAMEBOARD_PLAYER t
WHERE GAMEBOARD_ID = 987654;

SELECT USER, t.* FROM PCG_GAMEBOARD_COLOR t
WHERE GAMEBOARD_ID = 987654;

SELECT USER
     , t.Gameboard_ID 
     , t.Tile_Row
     , count(*)
     , min(t.Tile_Col)
     , max(t.Tile_Col)
     , max(t.Player_ID)
     , max(t.Color_Name)
  FROM PCG_GAMEBOARD_TILE t
 WHERE GAMEBOARD_ID = 987654
 GROUP BY t.Gameboard_ID, t.Tile_Row
 ORDER BY t.Gameboard_ID, t.Tile_Row;






